# Task 5

In [59]:
import matplotlib.pyplot as plt
from time import time
!pip install tqdm
from tqdm import tqdm
import numpy as np
from scipy import linalg as lg

## Task 5.1

In [41]:
def norm_vec_p(A, p):
    # np.seterr('raise')
    x = A**p
    x = np.sum(x)
    # print(x, np.float32(1/p))
    return np.power(x,(1/p))
    # return (np.sum(A**p))**(1/p)

def norma_Lp(A, p, n=500):
    norma = None
    for i in range(n):
        x = np.random.choice(np.linspace(-100, 100, 10000), A.shape[1])
        x /= norm_vec_p(x, 2)
        # print(A)
        # print(x)
        # print(A@x)
        tmp = norm_vec_p(A@x, p)
        if i == 0:
            norma = tmp
        else:
            if tmp > norma: norma = tmp
        # break
    return norma

def chisl_obus(A, p):
    return norma_Lp(A, p)*norma_Lp(linalg.inv(A), p)

# A = np.array([[1, 2, 3]])
A = np.arange(12).reshape((3,4))
x = []
y = []
for i in tqdm(range(15)):
    j = 2**i
    x.append(j)
    y.append(norma_Lp(A, 3, n=j))
    # print(j)

plt.plot(x, y)
plt.grid()
plt.xscale('log')
# plt.yscale('log')
plt.show()

  0%|          | 0/15 [00:00<?, ?it/s]


FloatingPointError: invalid value encountered in power

## Task 5.2


## Task 5.3


In [76]:
def cholesky(A):
    L = np.zeros_like(A)
    L[0,0] = np.sqrt(A[0,0])
    L[1:,0] = A[1:,0]/A[0,0]
    print('L:', L, lg.cholesky(A))
    for i in range(1, A.shape[0]):
        for j in range(1, i+1):
            if i == j:
                print(i, A[i,i] - np.sum(L[i,:i]**2))
                L[i,i] = np.sqrt(A[i,i] - np.sum(L[i,:i]**2))
            else:
                L[i,j] = (A[i,j] - np.sum(L[i,:j]*L[j,:j]))/L[j,j]
    print('----------------------')
    return L

def task3(cov):
    s = lg.cholesky(cov)
    z = np.random.normal(0, 1, cov.shape[0])

    return x

# A = np.random.randint(0, 10, (3,3))
# print(A@A.T)
# B = A*A.T
# print(A)
B = np.array([[1,1],[-1,1]])
B = B+B.T
print(B)
L = cholesky(B)
print(L)
print(L@L.T)

[[2 0]
 [0 2]]
L: [[1 0]
 [0 0]] [[1.41421356 0.        ]
 [0.         1.41421356]]
1 2
----------------------
[[1 0]
 [0 1]]
[[1 0]
 [0 1]]


## Task 5.4